name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Dependencies
      run: sudo apt-get install build-essential libxcb-shm0-dev libxcb-randr0-dev xcb git
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Archive build output
      run: tar -czvf build-output.tar.gz target/release/
    - name: Upload build output
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: build-output.tar.gz
