name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: windows-latest
            arch: x64
          - os: macos-latest
            arch: arm64
          - os: macos-latest
            arch: x64
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install build-essential libxcb-shm0-dev libxcb-randr0-dev xcb git libxcb1 libxrandr2 libdbus-1-3

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install -y mingw

    - name: Install dependencies (macOS)
      if: startsWith(matrix.os, 'macos')
      run: |
        brew install llvm

    - name: Create cargo bin directory (macOS)
      if: startsWith(matrix.os, 'macos')
      run: mkdir -p $HOME/.cargo/bin

    - name: Install Rustup (macOS)
      if: startsWith(matrix.os, 'macos')
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env

    - name: Set up Rust
      run: rustup update stable

    - name: Build
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Archive build output (Linux and macOS)
      if: matrix.os != 'windows-latest'
      run: |
        mkdir -p rencounter/
        cp target/release/rencounter_counter rencounter/
        cp text-detection.rten rencounter/
        cp text-recognition.rten rencounter/
        zip -r ${{matrix.os}}-${{matrix.arch}}.zip rencounter 

    - name: Archive build output (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        mkdir -p rencounter 
        cp target/release/rencounter_counter.exe rencounter/ 
        cp text-detection.rten rencounter/
        cp text-recognition.rten rencounter/ 
        Compress-Archive -Path rencounter -DestinationPath ${{ matrix.os }}-${{ matrix.arch }}.zip

    - name: Upload build output
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}
        path: ${{ matrix.os }}-${{ matrix.arch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: LS build directory
      run: |
        ls -R . 

    - name: Create tag
      id: create_tag
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        git tag $TAG_NAME
        git push origin $TAG_NAME
        echo "::set-output name=TAG::$TAG_NAME"

    - name: Set release name
      id: set_release_name
      run: echo "RELEASE_NAME=Release $(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.create_tag.outputs.TAG }}
        release_name: ${{ env.RELEASE_NAME }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Download Linux build artifact
      uses: actions/download-artifact@v4
      with:
        name: ubuntu-latest-x64
        path: ./

    - name: Download Windows build artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-latest-x64
        path: ./ 

    - name: Download macOS x64 build artifact
      uses: actions/download-artifact@v4
      with:
        name: macos-latest-x64
        path: ./ 

    - name: Download macOS arm64 build artifact
      uses: actions/download-artifact@v4
      with:
        name: macos-latest-arm64
        path: ./ 

    - name: Upload Linux Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ubuntu-latest-x64.zip
        asset_name: ubuntu-latest-x64.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: windows-latest-x64.zip
        asset_name: windows-latest-x64.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload macOS x64 Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: macos-latest-x64.zip
        asset_name: macos-latest-x64.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload macOS arm64 Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: macos-latest-arm64.zip
        asset_name: macos-latest-arm64.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
